apiVersion: tenant.rafaelmejia.me/v1
kind: Tenant
metadata:
  labels:
    app.kubernetes.io/name: k8s-tenant-operator
    app.kubernetes.io/managed-by: kustomize
  name: sample
spec:
  appImage: nginx:latest
  replicas: 3
  subdomain: sample
